### ISSUE TITLE
Size of klevu_order_sync

### ISSUE THREAD

**Issue by gustadev84** [klevu/productsearch#110]
Hi,

I'm using Klevu Product Search and the table klevu_order_sync is one of the biggest tables in the DB. I don't use the data from this table in my project; I understand it's used to sync data with Klevu. We've been storing data for years and my question is if it's ok to clear data with send as true and keep only the last months.

Thanks

**Comment by sandipklevu** [comment]
@gustadev84  yes your understanding is correct. 
You can keep last months data and its fine to clear the already send data with `send=1` if you do not use such data in your project.
Alternatively, you can take it look [here](https://github.com/klevu/metadata/blob/master/etc/adminhtml/system.xml#L17) and enable setting `Set "Yes" to send order data to Klevu when an order is successfully placed on the checkout page`.

**Comment by gustadev84** [comment]
Thanks @sandipklevu
