### ISSUE TITLE
Duplicate test

### ISSUE THREAD

**Issue by Zifius** [klevu/productsearch#111]
There is a duplicated test in [../Test/Integration/Model/Product/ResourceModel](https://github.com/klevu/productsearch/tree/3.x/Test/Integration/Model/Product/ResourceModel) directory which prevents installation on case-insensitive file systems such as macOS

The following error is emitted upon installation:

```
  - Installing klevu/module-productsearch (3.6.2): Extracting archive
    Failed to extract klevu/module-productsearch: (1) '/usr/bin/unzip' -qq '/Users/alexanderturiak/Projects/{Redacted}/Source-Staging2/vendor/composer/tmp-dfdaf70aebce24532b1822ca2aa938ab.zip' -d '/Users/alexanderturiak/Projects/{Redacted}/Source-Staging2/vendor/composer/6f92a137'

replace /Users/alexanderturiak/Projects/{Redacted}/Source-Staging2/vendor/composer/6f92a137/Test/Integration/Model/Product/ResourceModel/GetParentProductRelationsTest.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

**Comment by klevu** [comment]
@Zifius Thank you for reporting this, you're absolutely correct `getParentProductRelationsTest.php` should not be there.
We'll get that removed.
-RH

**Comment by klevu** [comment]
@Zifius That has been fixed in the latest release https://github.com/klevu/productsearch/pull/113
https://github.com/klevu/productsearch/releases/tag/3.6.3
Again, thank you for reporting this issue.
- RH
