### ISSUE TITLE
Version 3.6.3 broke PHP <= 7.4 compatibility

### ISSUE THREAD

**Issue by gocom** [klevu/productsearch#114]
Version 3.6.3 contains small syntax regression, which causes a fatal syntax error on PHP 7.4 and older. Project's composer.json states that it should still support PHP 7 versions.

The module version 3.6.3 will happily try to install on PHP 7, but runtime will crash in the syntax error, when running into the introduced PHP >= 8 syntax.

The syntax error is caused by the trailing constructor argument comma in JsVariables class:
https://github.com/klevu/productsearch/blob/2c3ff7a779c7e8a9d8b1318a0a990a4cb0cd6e82/Block/Html/Head/ThemeV2/JsVariables.php#L72

**Comment by klevu** [comment]
@gocom Thank you for reporting this, well get that removed in the next release.
-RH

**Comment by klevu** [comment]
@gocom This has been fixed in the latest release
