### ISSUE TITLE
Typo? Tires / Tiers

### ISSUE THREAD

**Issue by benyanke** [klevu/productsearch#12]
![image](https://user-images.githubusercontent.com/4274911/40324425-0f494630-5cfe-11e8-9364-68b3117f085a.png)

**Comment by sandipklevu** [comment]
Thank you for raising this concern with us.
We have handled it along with other improvements in the latest Klevu versions. 
Please update to the latest version [2.3.14](https://github.com/klevu/klevu-smart-search-M2/releases/tag/2.3.14).
