### ISSUE TITLE
Feature Request: Progress on sync page

### ISSUE THREAD

**Issue by benyanke** [klevu/productsearch#13]
https://github.com/klevu/productsearch/blob/master/view/frontend/templates/klevu/search/ajaxsync.phtml#L27

Right now, there's no indication of the progress. Perhaps it would be helpful if there was a percentage progress available or at the very least, an indication of how many requests have run.

**Comment by klevu** [comment]
Hi. thank you for the suggestion. this improvement is in our road map and will complete in the near future. unfortunately, we can not define any timeline for this now.
