### ISSUE TITLE
Error in UpgradeSchema

### ISSUE THREAD

**Issue by ubalodis** [klevu/productsearch#15]
After upgrading module to 2.2.8 setup:upgrade produces the following error

`SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key, query was: ALTER TABLE `klevu_product_sync` DROP PRIMARY KEY`

**Comment by klevu** [comment]
It looks to website specific issue. we are closing this issue
