### ISSUE TITLE
Elasticsearch6 as search engine no handled correctly

### ISSUE THREAD

**Issue by sdesmet** [klevu/productsearch#16]
Hi,

The [following method](https://github.com/klevu/productsearch/blob/38d7022f98ab2d411ef22881bf22e2d9194cf9fd/Framework/Request/Cleaner.php#L85) is not handling "elasticsearch6" as the value for `catalog/search/engine` config key, which causes the query to be done against terms `entity_id` and renders no results.

Thanks

**Comment by sandipklevu** [comment]
Thank you for raising this concern with us.

We have handled it along with other improvements in the latest Klevu versions. Please update to the latest version [2.2.22.](https://github.com/klevu/klevu-smart-search-M2#version-2222)

Reach out to us on email support@klevu.com if you require further help.
