### ISSUE TITLE
Array sizes are inconsistent when running multisort

### ISSUE THREAD

**Issue by subbu1993** [klevu/productsearch#17]
### Preconditions

- Magento 2.3.4
- Klevu - 2.2.19
- Stores > Config > klevu > Search Settings > Search Result Page settings > Use klevu relevance 
- Stores > Config > klevu > Search Settings > Search Result Page settings > Preserve your theme layout

### issue

- When rendering search results page a PHP warning is thrown 

```
Warning: array_multisort(): Array sizes are inconsistent in vendor/klevu/module-productsearch/Plugin/Api/Search/SearchResult.php on line 59
```

### Fix

This is happening because 2 or more products have the same score value causing the array in the multisort to not be the same size as the result array

We suggest using a unique key for each score value 

```
$result_key[$key] = $item->getCustomAttribute("score")->getValue(); 
$key++;
```

in https://github.com/klevu/productsearch/blob/e37568fcc6b1c3862eb21098d9cfdecebaaae7d1/Plugin/Api/Search/SearchResult.php#L53

`$key` is initialized to 0 outside the for loop

**Comment by sandipklevu** [comment]
Thank you for raising this issue with us.

We have handled it in the Klevu [2.2.22](https://github.com/klevu/klevu-smart-search-M2#version-2222) version. Please update to the latest version.

Reach out to us on email support@klevu.com if you require further help.
