### ISSUE TITLE
Native Magento Search Suggestions

### ISSUE THREAD

**Issue by chris-huffman** [klevu/productsearch#18]
It looks like there was a "fix" implemented by the `disableautosuggest.js` file to set the minSearchLength to 200 so that native search suggestion requests aren't triggered. However, in Magento 2.3.5 (Commerce) this "fix" no longer seems to work. This means that the native search suggestion ajax request is triggering alongside the request to Klevu. So far, I've got around this by simply updating the corresponding configuration setting in admin to be 200. However, I'm not sure if this is the ideal solution.

**Comment by sandipklevu** [comment]
Thank you @chris-huffman for raising this concern with us. We have handled this in the [Klevu 2.3.4](https://github.com/klevu/productsearch/releases/tag/2.3.4) version. 

Reach out to us on email support@klevu.com if you need further assistance.
