### ISSUE TITLE
Usage of \Zend\Log\Logger causing errors

### ISSUE THREAD

**Issue by batmike** [klevu/productsearch#28]
There are a few usages of the old \Zend\Log\Logger still instead of being replaced by the Klevu LoggerConstants:

- Model/Config/Backend/Trigger.php at Line 83
- Model/Order/Sync.php at Lines 372, 382 and 393

Replacing those mentions with LoggerConstants clears up the errors occuring during the order sync process and also when trying to open the backend config page.

**Comment by davidg-klevu** [comment]
Hi Mike

Thanks for this report - we've brought this into our flow as a priority and will get an updated version out shortly

Thanks again

**Comment by batmike** [comment]
@davidg-klevu - Great! Thanks for the update.

**Comment by klevu** [comment]
@batmike Thanks again for the report. You should find this issue resolved in the latest version (2.4.4) released now

**Comment by batmike** [comment]
Thanks for the quick updates!
