### ISSUE TITLE
File has incorrect additional <?php tags & duplicated code

### ISSUE THREAD

**Issue by chickenland** [klevu/productsearch#6]
Compilation within Magento 2.2 fails due to productsearch/Controller/Adminhtml/Download/Logdownload.php being corrupt in version 2.2.23

**Comment by vlad1992** [comment]
Confirmed. this breaks bin/magento setup:di:compile

**Comment by georgeschiopu** [comment]
Was just about to open an issue with this...

**Comment by georgeschiopu** [comment]
Looks like it was addresses here: https://github.com/klevu/productsearch/pull/5
