### ISSUE TITLE
Invalid Cron Syntax

### ISSUE THREAD

**Issue by bap14** [klevu/productsearch#65]
There is a trailing slash in one of the cron schedule options which causes an error.

https://github.com/klevu/productsearch/blob/19a474b4ec5b459de5158ec7483d1d50b1d7beb3/etc/di.xml#LL227C19-L227C20

**Comment by klevu** [comment]
@bap14 Thank you for reporting this. It has finally been fixed in the latest releases 2.11.0 and 3.3.0.
