### ISSUE TITLE
Filter issues

### ISSUE THREAD

**Issue by chickenland** [klevu/productsearch#7]
When applying filters on category pages with Magento 2.2EE and Klevu 2.1.22.  The IndexBuilder (Model/Search/IndexBuilder) appears to cause issues when filters are applied.  For example, applying a size attribute filter, causes the following error to be thrown:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'size_filter.value' in 'where clause', query was: INSERT INTO `search_tmp_59f89571894ff0_15825268` SELECT `main_select`.`entity_id`, SUM(score) AS `relevance` FROM (SELECT `search_index`.`entity_id`, (((0) + (0) + (0)) * 1) AS `score` FROM `catalogsearch_fulltext_scope1` AS `search_index`
 LEFT JOIN `catalog_eav_attribute` AS `cea` ON search_index.attribute_id = cea.attribute_id
 INNER JOIN `catalog_category_product_index` AS `category_ids_index` ON search_index.entity_id = category_ids_index.product_id AND category_ids_index.store_id = '1' WHERE (category_ids_index.category_id = 69) AND (size_filter.value = '202')) AS `main_select` GROUP BY `entity_id` ORDER BY `relevance` DESC, `entity_id` DESC
 LIMIT 10000

Disabling Klevu appears to currently fix the issue, so it appears that this isn't triggering an extra table somewhere?

**Comment by tejasklevu** [comment]
Hi. Please note, Klevu search module does not make any changes to DB, it just modifies the collection query only on the catalog search page.
there is no use of "search_index" in Klevu module as well.
It can be the issue regarding installation of the Magento system.

**Comment by chickenland** [comment]
@tejasklevu it looks like Model/Search/IndexBuilder.php - build() / __construct() isn't compatible with 2.2?  Removing your build() function and implementing the new __construct() signature allows the page to load, but I'm assuming now breaks some Klevu functionality?

**Comment by tejasklevu** [comment]
Hi @chickenland .To investigate the matter further, could you please share website access with us where you are getting this issue? Also please share the screenshot of error with the page URL where the error is occurring.

**Comment by chickenland** [comment]
@tejasklevu This is currently occuring on https://www.customplugs.com/clothing/t-shirts - select any filter on the left menu.

<img width="1669" alt="screen shot 2017-11-16 at 10 05 04" src="https://user-images.githubusercontent.com/649590/32885547-b8336284-cab5-11e7-90c4-b19ecdec668b.png">

**Comment by elvinristi** [comment]
I don't think Klevu is M2.2 ready.

By comparing vendor/magento/module-catalog-search/Model/Search/IndexBuilder.php classes between 2.1.9 and 2.2.0 then they are very different.

Also for some reason this class has been overridden and not used Plugins

```
	<preference for="Magento\CatalogSearch\Model\Search\IndexBuilder" 
				type="Klevu\Search\Model\Search\IndexBuilder"/>	
```

Should be changed to use plugin and i.e. aroundBuild() function.

**Comment by tejasklevu** [comment]
Hi Guys.Thank you for the message.we are looking into it and get back to you shortly.

**Comment by tejasklevu** [comment]
@chickenland we have found the intermediate and trial solution for only Magento 2.2EE now. Can you please replace the Klevu\Search\Model\Search\IndexBuilder.php file with the attached one?

@elvinristi hi Elvin. We are testing with other Magento version and compatibility. We will release the most stable solution for this in our next release.thanks again

**Comment by tejasklevu** [comment]
[IndexBuilder.zip](https://github.com/klevu/productsearch/files/1478900/IndexBuilder.zip)

**Comment by chickenland** [comment]
Thanks @tejasklevu I'll take a look.

**Comment by chickenland** [comment]
@tejasklevu Initial testing, that looks to have done the trick.  Is there likely to be a release soon, or should I patch this manually? (coming from composer).

**Comment by klevu** [comment]
@chickenland we have fully restructured that part of the code and are no longer using the index override.
