### ISSUE TITLE
Query on Plugin use

### ISSUE THREAD

**Issue by gene-roussetos** [klevu/productsearch#72]
https://github.com/klevu/productsearch/blob/6046055458bcd6264939ce9c1158805afe91184f/Model/Product/LoadAttribute.php#L392

Hi, we are trying to use an after plugin on the provided method and add data to the `product` array data on the method linked (v2.9.3).
Either our understanding of use for the method is incorrect (it's not for Plugins to hook) or this is not working as expected?

Might be better if this was just a standard `$product = $this->processProductAfter($product, $parent, $item)` to allow plugins to hook into?

Apologies if the question seems silly, but my colleagues & I were trying to figure out why after plugin was not working as expected.
THe plugin was triggered and the data were assigned internally, but on the parent method the new array values were missing from `$product`

**Comment by klevu** [comment]
Hi @gene-roussetos. 

You are absolutely correct, this would be much better as `$product = $this->processProductAfter($product, $parent, $item)`. Passing those parameters by reference is exactly what is causing the after plugin not to work. 

We'd love to remove this, however as this is public code it has the potential to break other merchants' sites if we swapped that out. This was a decision made a long time ago and for this version of the module, we are unfortunately stuck with it.

What you can do is extend the `LoadAttributes` class containing just the `processProductAfter` method and preference out the Klevu `LoadAttribute` class with your newly created one.

Richard H.

**Comment by gene-roussetos** [comment]
@klevu thank you very much for you response.

Currently we made a composer patch for this to change the method to be `$product = $this->...` to get our plugin working as we wanted to avoid preferences.

Hopefully this will change in a future MAJOR version

**Comment by klevu** [comment]
This will definitely change in the next MAJOR version :-)
I'll close this ticket, if you need anything else please feel free to reopen it.
