### ISSUE TITLE
mismatch in getDefaultMappedAttributes array

### ISSUE THREAD

**Issue by Seppo-Konttinen-Solteq** [klevu/productsearch#74]
Hi.

We have version 3.2.1.

I noticed in:

vendor/klevu/module-productsearch/Helper/Config.php:getDefaultMappedAttributes

that the mapping array does not match between Magento and Klevu attributes. After second 'price' in Magento attributes there is 'tax_class_id' when in Klevu side there is 'salePrice'. Copy + paste problem I guess as 'salePrice' is also before it. Also should final price from Magento side to be mapped to 'salePrice' anyway?

`return [
            "magento_attribute" => [
                "name",
                "sku",
                "image",
                "small_image",
                "media_gallery",
                "status",
                "description",
                "short_description",
                "price",
                "price",
                "tax_class_id",
                "weight",
                Rating::ATTRIBUTE_CODE,
                ReviewCount::ATTRIBUTE_CODE,
                "special_price",
                "special_from_date",
                "special_to_date",
                "visibility",
                "created_at"
            ],
            "klevu_attribute" => [
                "name",
                "sku",
                "image",
                "small_image",
                "media_gallery",
                "status",
                "desc",
                "shortDesc",
                "price",
                "salePrice",
                "salePrice",
                "weight",
                Rating::ATTRIBUTE_CODE,
                'rating_count',
                "special_price",
                "special_from_date",
                "special_to_date",
                "visibility",
                "dateAdded"
            ]
        ];`

**Comment by klevu** [comment]
@Seppo-Konttinen-Solteq thanks for the report. This has been passed to our development team to investigate.

**Comment by klevu** [comment]
Hi @Seppo-Konttinen-Solteq, 

We have taken a look at this issue and while you are right those attributes are not mapped correctly, the prices in the feed do not use the mapped fields, but call other methods to get the price data. e.g. https://github.com/klevu/productsearch/blob/3.x/Model/Product/LoadAttribute.php#L890

Unless you're seeing incorrect data being sent to Klevu I think we can close this off. We are in the process of rebuilding the indexing/feed and a new, much improved, version will be released later in the year.

**Comment by Seppo-Konttinen-Solteq** [comment]
@klevu thanks for the info. I just stumbled on that when debugging different thing so I think this is save to close.
