### ISSUE TITLE
Error: Multi dimensional array provided for "other" attribute

### ISSUE THREAD

**Issue by erlisdhima** [klevu/productsearch#86]
Below error is thrown in the log files:  

```
Klevu.ERROR: Klevu\Search\Model\Api\Action\Addrecords::prepareOtherParameters: Multi dimensional array provided for "other" attribute for SKU ... . [] []
```

Adobe Commerce version: 2.4.6-p1
Klevu version: 3.3.3

**Comment by sandipklevu** [comment]
@erlisdhima  It may be data specific concern. Seems like for a given SKU, one of the attribute returning the multi-dimensional values.

```
LoggerConstants::ZEND_LOG_ERR,
    __(
        '%1: Multi dimensional array provided for "other" for SKU %2 : attribute %3.',
        __METHOD__,
        $record['sku'],
        $key
    )
```
    
`SKU` and `attribute` should have logged in the `%2` and `%3` respectively.

**Comment by erlisdhima** [comment]
@sandipklevu The problem is that the product data is the same for us. This error started happening after we updated the klevu module from 3.2.1 to 3.3.2.
Updating to 3.3.3 on our STG env has not made any difference.

Products are still being synced. I'm assuming this is trying to sync the attributes, and erroring on a specific attribute, and throws a general message - 'other' attribute ?

I also see "attribute %3." in the code snippet above, but this is not logged in the logs. Checking the latest version of Klevu, the message has changed and does not include "attribute %3."

**Comment by sandipklevu** [comment]
@erlisdhima Yes, that is the correct assumption.
Please note, it won't affect the product sync even for erroneous SKU.
In the previous versions, attribute was not logging so was difficult to find which attribute causing it. This has been improvised in 3.3.3.

I can see `attribute %3` has been added to the latest release.
https://github.com/klevu/productsearch/commit/38c5f276d8033ef9dfa07c7c7bcf67d7ae6899ba

If you still require further investigation, write us to support@klevu.com with more details.

**Comment by erlisdhima** [comment]
@sandipklevu , sorry, I was looking at the wrong method!
Also I dont see the error since the update this morning (logs are in UTC time, so I mistakenly thought they were present after the update). 
I will monitor this in the next few days and close this issue if its not present anymore.

Thanks for sharing the support email!

**Comment by erlisdhima** [comment]
@sandipklevu I'm closing this. Thanks for your help!
