### ISSUE TITLE
Product sync is ignoring "is_exclude_cat" category attribute.

### ISSUE THREAD

**Issue by kzulis** [klevu/productsearch#88]
It seems that there's a bug in `Klevu\Search\Model\Product\Product::getCategoryPaths`, it's using _getIsExclude**d**Cat_ but it probably should be _getIsExcludeCat_ as category attribute code is `is_exclude_cat`.

Change was introduced in [this commit](https://github.com/klevu/productsearch/commit/f54c20ff4e3f8842466c41e33cad6df3922467cc#diff-26c9743c55d0325686edf07c13bc044a3afa23c8bbda81534014591fc3c6b0c7).

**Comment by sandipklevu** [comment]
Hi @kzulis,  Thank you for reporting this.
This will certainly be fixed in the next version.

**Comment by AJ-Klevu** [comment]
Hi @kzulis 

This has been handled in the latest releases 2.12.0 and 3.4.0.
Thank you again for flagging this.
