### ISSUE TITLE
Question: Too late for the schedule

### ISSUE THREAD

**Issue by avra911** [klevu/productsearch#9]
Hello,

We set `Europe/Stockholm` in both php configuration as well as in server system tzdata setup.

However the cron `klevu_search_product_sync` is schedule with 1h in advanced always and is receiving all the time the message `Too late for the schedule`, see: https://s.nimbus.everhelper.me/share/1258888/l0fwzn69k6bob6eybt4e.

Maybe this is expected results, because in config is set to run at `0 */3 * * *` (every 3 hours). Even so, it looks weird to be set for an hour in the past?

**Comment by elvinristi** [comment]
Same issue. I can see that in cron_schedule table when I click the button in admin to Sync all then entry will be added in other timezone than are the items there.

Issue comes from Sync::schedule($time = "now") which manipulates directly cron_schedule table and not respecting the core functionality.

Instead the time should be similar to:

    $scheduledAt = $this->timezone->scopeTimeStamp();

where timezone is `\Magento\Framework\Stdlib\DateTime\TimezoneInterface`

**Comment by klevu** [comment]
@elvinristi & @avra911 thanks you for the information. We have patched this issue in the latest release of the module.
Please let us know if you still encounter issues in the future.
