### ISSUE TITLE
Confusing CLI command description in klevu:syncdata

### ISSUE THREAD

**Issue by szagabesz** [klevu/productsearch#95]
The command `klevu:syncdata` states it will sync even CMS pages too,
https://github.com/klevu/productsearch/blob/8dab5ea8eb5e501e52920f94dcd7d8dee3eda83b/Console/Command/SyncCommand.php#L128

 but apparently CMS data won't be synced via this command, because that part is commented out:
https://github.com/klevu/productsearch/blob/8dab5ea8eb5e501e52920f94dcd7d8dee3eda83b/Console/Command/SyncCommand.php#L250

I suggest to remove the CMS from the description or put back the commented out CMS synchronisation call.

**Comment by sandipklevu** [comment]
Hi @szagabesz,

Thanks for reporting to us.

This has been handled in the [3.5.x](https://github.com/klevu/klevu-smart-search-M2/tree/3.5.0)/[2.13.0](https://github.com/klevu/klevu-smart-search-M2/tree/2.13.0) release.
CMS text removed from description.
